
import { z } from "zod";

/* ============================================================
   1️⃣ PRODUCT INFO SCHEMA (ProductInfo Model)
   ============================================================ */

const productInfoSchema = z.object({
  store_id: z.string().uuid(),
  warehouse_id: z.string().uuid(),

  product_name: z.string().min(2),
  slug: z.string().optional(),  // generated by backend
  sku: z.string().optional(),   // generated by backend

  category_id: z.string().uuid(),
  subcategory_id: z.string().uuid(),   // REQUIRED in model
  brand_id: z.string().uuid(),         // REQUIRED
  unit_id: z.string().uuid(),          // REQUIRED

  barcode_symbology_id: z.string().uuid(),

  selling_type: z.enum(["online", "pos"]),
  description: z.string().optional(),
});


/* ============================================================
   2️⃣ SINGLE PRODUCT SCHEMA (SingleProduct Model)
   ============================================================ */

const singleProductSchema = z.object({
  quantity: z.number().int().nonnegative(),
  quantity_alert: z.number().int().nonnegative(),

  price: z.number().nonnegative(),

  tax_id: z.string().uuid(),
  tax_type: z.enum(["inclusive", "exclusive"]),

  discount_type: z.enum(["percentage", "fixed"]),
  discount_value: z.number().nonnegative(),
});


/* ============================================================
   3️⃣ VARIANT PRODUCT SCHEMA (VariantProduct Model)
   ============================================================ */

const variantProductSchema = z.object({
  attribute_name: z.string().min(1, "Attribute name is required"),
  attribute_value: z.string().min(1, "Attribute value is required"),

  sku: z.string().min(1),

  barcode_symbology_id: z.string().uuid(),

  quantity: z.number().int().nonnegative(),
  quantity_alert: z.number().int().nonnegative(),

  price: z.number().nonnegative(),

  tax_id: z.string().uuid(),
  tax_type: z.enum(["inclusive", "exclusive"]),

  discount_type: z.enum(["percentage", "fixed"]),
  discount_value: z.number().nonnegative(),
});


/* ============================================================
   4️⃣ PRODUCT IMAGE SCHEMA (ProductImage Model)
   ============================================================ */

const productImageSchema = z.object({
  image_url: z.string().url({ message: "Image URL must be valid" }),
});


/* ============================================================
   5️⃣ CUSTOM FIELDS SCHEMA (CustomFields Model)
   ============================================================ */

const customFieldsSchema = z.object({
  warranty_id: z.string().uuid(),
  manufacturer: z.string().min(1),
  manufactured_date: z.string(), // ISO date string
  expiry_on: z.string(),         // ISO date string
});


/* ============================================================
   FULL PRODUCT SCHEMAS (CREATE + UPDATE)
   ============================================================ */

// ✔ Create Product
export const createProductSchema = z.object({
  productInfo: productInfoSchema,
  singleProduct: singleProductSchema.optional(),
  variantProducts: z.array(variantProductSchema).optional(),
  images: z.array(productImageSchema).optional(),
  customFields: customFieldsSchema.optional(),
});

// ✔ Update Product (PATCH)
export const updateProductSchema = z.object({
  productInfo: productInfoSchema.partial(),
  singleProduct: singleProductSchema.partial().optional(),
  variantProducts: z.array(variantProductSchema.partial()).optional(),
  images: z.array(productImageSchema).optional(),
  customFields: customFieldsSchema.partial().optional(),
});

// ✔ ID Validation
export const idSchema = z.object({
  id: z.string().uuid(),
});
